//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOrder()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int purchaseordernumber { get; set; }
        public string suppliercode { get; set; }
        public int storeclerkcode { get; set; }
        public System.DateTime orderdate { get; set; }
        public Nullable<double> totalcost { get; set; }
        public Nullable<int> approvercode { get; set; }
        public Nullable<System.DateTime> approvaldate { get; set; }
        public Nullable<System.DateTime> expecteddeliverydate { get; set; }
        public string deliveryordernumber { get; set; }
        public Nullable<System.DateTime> deliverydate { get; set; }
        public Nullable<int> receivercode { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
