//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int transactionid { get; set; }
        public string itemcode { get; set; }
        public System.DateTime date { get; set; }
        public string deptsupplier { get; set; }
        public int quantitychange { get; set; }
        public int balance { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
